language: python

install:
  - sudo pip install --upgrade setuptools
  - sudo pip install -r test_requirements.txt

script:
  - pwd
  - py.test ./tests -v --cov --cov-report=term-missing

after_success:
  - coveralls