language: python

install:
  - sudo pip install --upgrade setuptools
  - sudo pip install coverage python-coveralls pytest-cov pytest pytest-pep8

script:
  - pwd
  - py.test ./tests -v --cov --cov-report=term-missing

after_success:
  - coveralls