language: python

install:
  - pip install --upgrade setuptools
  - pip install -r test_requirements.txt
script:
  - export PYTHONPATH=$(pwd)
  - py.test ./tests -v --cov --cov-report=term-missing

after_success:
  - coveralls